

@client_id = Nordlo
@client_secret = 6s2W4SWwtwjeT8uEfJ9ABSUTsrp48dEA

# Client authorization request
POST https://sandbox-auth.smaapis.de/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&client_secret={{client_secret}}&grant_type=client_credentials


###
GET https://nordlo-solar.azurewebsites.net/oauth/access